// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdiawnvjzbosxboqeyer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaWF3bnZqemJvc3hib3FleWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzY1OTMsImV4cCI6MjA2NDYxMjU5M30.y0idv1kZyePDgfrvCohI7qRSl_jU50kqxbitmcgVLo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);